blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/amaechiu-del/Vittual-Arena/discussions
    about: Please use GitHub Discussions for questions and general discussions
